# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[\\[](bold black)\
$username\
[@](bold white)\
$hostname\
[\\]](bold black)\
[\\[](bold black)\
$directory\
[\\] ](bold black)\
$fill\
$git_status\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$sudo\
$status\
$time\
$line_break\
$character"""

add_newline = false

[time]
format = ' [$time]($style) '
disabled = false
use_12hr = true

[username]
style_user = 'cyan'
style_root = 'red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](cyan)'
disabled = false

[directory]
format = '[$path](cyan)'

[git_status]
format = ' ([[\[](bold black)$all_status$ahead_behind[\]](bold black)]($style) )'
modified = '[$count!](bold yellow)'
ahead = '[$count⇡](bold yellow)'
untracked = '[$count?](bold purple)'
renamed = '[$count»](bold purple)'
staged = '[$count+](bold green)'

[git_branch]
style = 'bold black'
format = '[$symbol](bold green) [$branch(:$remote_branch)]($style)'
symbol = ''
# truncation_length = 16
truncation_symbol = '…'
