[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1.0
option_as_alt = "OnlyLeft"

[window.padding]
x = 2
y = 2
