[settings.node]
mirror_url = "https://ukgartifactory.pe.jfrog.io/artifactory/nodejs-org-dist/"

[env]
DAGGER_NO_NAG="1"
DO_NOT_TRACK="1"
NODE_EXTRA_CA_CERTS="{{env.HOME}}/ukg/certs/ukg.pem"

[tasks.claude]
description = "litellm - claude"
quiet = true
dir = "{{cwd}}"
run = '''
export NODE_USE_SYSTEM_CA=1
export NODE_EXTRA_CA_CERTS="$HOME/ukg/certs/ukg.pem"

export JIRA_MCP_AUTH_TOKEN="$(fnox get --profile=local JIRA_AUTH_TOKEN)"
export ENGPORTAL_USER_EMAIL="david.pitoniak@ukg.com"

claude "$@"
'''

[tasks.jctx]
description = "put ticket number onto clipboard"
quiet = true
run = 'jctx --token="$(fnox get --profile=local JIRA_AUTH_TOKEN)"'

[tasks.docker-build]
quiet = true
usage = '''
arg <image-tag>
'''
run = '''
export ARTIFACTORY_AUTH_TOKEN="$(fnox get ARTIFACTORY_AUTH_TOKEN)"
(
  set -x
  docker build --secret id=artifactory_auth_token,env=ARTIFACTORY_AUTH_TOKEN . -t "$usage_image_tag"
)
'''
